replicaCount: 2

env:
  springProfilesActive: ckc
  lifecycleWorkerConcurrency: 50
  lifecyclePollLoopConcurrency: 1
  lifecycleWorkChannelCapacity: 512
  telemetryWorkerConcurrency: 50
  telemetryPollLoopConcurrency: 1
  telemetryWorkChannelCapacity: 1

resources:
  requests:
    cpu: "1"
    memory: 1Gi
  limits:
    cpu: "1"
    memory: 2Gi

probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    failureThreshold: 8
  startup:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 30

hpa:
  enabled: false
