replicaCount: 1

env:
  delayP90Ms: 20
  delayP95Ms: 40
  delayP99Ms: 80
  delayP100Ms: 120
  errorRatePercent: 0

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
