replicaCount: 2

env:
  springProfilesActive: ckc
  orderProcessingMode: AT_LEAST_ONCE_KEY_ORDERING
  telemetryProcessingMode: FRESHNESS_FIRST_DROP_OLDEST

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: "2"
    memory: 2Gi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  scaleDownStabilizationWindowSeconds: 600
