replicaCount: 1

env:
  springProfilesActive: spring-kafka
  orderProcessingMode: AT_LEAST_ONCE_PARTITION_ORDERING
  batchProcessingMode: AT_LEAST_ONCE_PARTITION_ORDERING

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
