replicaCount: 1

image:
  repository: ckc-perf/demo-stubs
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  redisHost: ckc-external-redis.ckc-perf.svc.cluster.local
  redisPort: 6379

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    memory: 512Mi
