replicaCount: 1

lab:
  kafkaTopics:
    - name: order.events.v1
      partitions: 1
    - name: batch.events.v1
      partitions: 1
    - name: cauldron.events.v1
      partitions: 1

env:
  springProfilesActive: ckc
  orderProcessingMode: AT_LEAST_ONCE_ORDERED_BY_KEY
  telemetryProcessingMode: FRESHNESS_FIRST

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
