replicaCount: 1

env:
  springProfilesActive: spring-kafka
  orderProcessingMode: AT_LEAST_ONCE_ORDERED_BY_PARTITION
  batchProcessingMode: AT_LEAST_ONCE_ORDERED_BY_PARTITION

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
