replicaCount: 3

env:
  springProfilesActive: spring-kafka
  orderProcessingMode: AT_LEAST_ONCE_ORDERED_BY_KEY
  telemetryProcessingMode: FRESHNESS_FIRST

  orderPollLoopConcurrency: 10
  telemetryPollLoopConcurrency: 50
  batchPollLoopConcurrency: 6


resources:
  requests:
    cpu: "1"
    memory: 1Gi

probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    failureThreshold: 8
  startup:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 30

hpa:
  enabled: false
