replicaCount: 2

lab:
  kafkaTopics:
    - name: order.events.v1
      partitions: 56
    - name: batch.events.v1
      partitions: 44
    - name: cauldron.events.v1
      partitions: 64

env:
  springProfilesActive: spring-kafka
  orderProcessingMode: AT_LEAST_ONCE_PARTITION_ORDERING
  batchProcessingMode: AT_LEAST_ONCE_PARTITION_ORDERING
  orderPollLoopConcurrency: 28
  batchPollLoopConcurrency: 22
  telemetryPollLoopConcurrency: 32


resources:
  requests:
    cpu: "1"
    memory: 1Gi

probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    failureThreshold: 8
  startup:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 30

hpa:
  enabled: false
