apiVersion: batch/v1
kind: Job
metadata:
  name: ckc-kafka-init
  namespace: ckc-app
  labels:
    app.kubernetes.io/instance: ckc-kafka-init
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kafka-init
          image: apache/kafka:3.7.2
          command:
            - /bin/bash
            - -lc
            - |
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server ckc-kafka.ckc-app.svc.cluster.local:9092 --create --if-not-exists --topic potion.orders.lifecycle.v1 --partitions 6 --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server ckc-kafka.ckc-app.svc.cluster.local:9092 --create --if-not-exists --topic potion.cauldrons.telemetry.v1 --partitions 6 --replication-factor 1
