name: 3000tps_15min_chaos

stubs:
  error_rate_percent: 0
  eta:
    delay_p90_ms: 25
    delay_p95_ms: 40
    delay_p99_ms: 160
    delay_p100_ms: 300
  flavour:
    delay_p90_ms: 4
    delay_p95_ms: 6
    delay_p99_ms: 8
    delay_p100_ms: 50
  registry:
    delay_p90_ms: 2
    delay_p95_ms: 3
    delay_p99_ms: 4
    delay_p100_ms: 5

capacity_model:
  average_processing_ms:
    order: 2
    batch: 5
    telemetry: 35

load_test:
  shards: 1
  workers: 8
  base_tps: 3000
  order_event_percent: 35
  batch_event_percent: 25
  cauldron_telemetry_percent: 40
  telemetry_source_mode: FIXED_FLEET
  load_profile: "0 -> (3m, warmup) -> 100 -> (10m, maximum) -> 100 -> (2m, cool-down) -> 0"
  cauldron_count: 75
  min_orders_per_batch: 4
  max_orders_per_batch: 8
  min_brewing_steps: 5
  max_brewing_steps: 10
  diagnostics_blob_size: 256

chaos_steps:
  - at: 180s
    type: delete_random_pod
  - at: 360s
    type: set_stubs_profile
    params:
      error_rate_percent: 5
      eta:
        delay_p90_ms: 200
        delay_p95_ms: 400
        delay_p99_ms: 800
        delay_p100_ms: 1200
      flavour:
        delay_p90_ms: 200
        delay_p95_ms: 400
        delay_p99_ms: 800
        delay_p100_ms: 1200
      registry:
        delay_p90_ms: 20
        delay_p95_ms: 40
        delay_p99_ms: 80
        delay_p100_ms: 120
  - at: 480s
    type: crash_random_pod
  - at: 600s
    type: reset_stubs_profile
