name: ckc-baseline-internal

deployment:
  app_profile: spring-kafka-local-baseline
  stubs_profile: baseline
  kafka_topics:
    - name: order.events.v1
      partitions: 14
    - name: batch.events.v1
      partitions: 10
    - name: cauldron.events.v1
      partitions: 150


load_test:
  shards: 1
  workers: 8
  base_tps: 2000
  order_event_percent: 35
  batch_event_percent: 25
  cauldron_telemetry_percent: 40
  telemetry_source_mode: FIXED_FLEET
  load_profile: "0 -> (1m, warmup) -> 100 -> (10m, internal-baseline) -> 100 -> (1m, cool-down) -> 0"
  cauldron_count: 75
  min_orders_per_batch: 4
  max_orders_per_batch: 8
  min_brewing_steps: 5
  max_brewing_steps: 10
  diagnostics_blob_size: 256
