replicaCount: 2

lab:
  kafkaTopics:
    - name: order.events.v1
      partitions: 2
    - name: batch.events.v1
      partitions: 2
    - name: cauldron.events.v1
      partitions: 2

env:
  springProfilesActive: ckc
  orderWorkerConcurrency: 20
  orderPollLoopConcurrency: 1
  orderWorkChannelCapacity: 1024
  batchWorkerConcurrency: 20
  batchPollLoopConcurrency: 1
  batchWorkChannelCapacity: 1024
  telemetryWorkerConcurrency: 30
  telemetryPollLoopConcurrency: 1
  telemetryWorkChannelCapacity: 1024

resources:
  requests:
    cpu: "1"
    memory: 1Gi

probes:
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 12
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    failureThreshold: 8
  startup:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 30

hpa:
  enabled: false
