name: ckc-baseline-local

deployment:
  app_profile: ckc-local-baseline
  stubs_profile: baseline
  kafka_topics:
    - name: potion.orders.lifecycle.v1
      partitions: 4
    - name: potion.cauldrons.telemetry.v1
      partitions: 4

load_test:
  shards: 1
  lifecycle_base_rate: 10
  telemetry_base_rate: 10
  load_profile: "0 -> (1m, warmup) -> 100 -> (10m, local-baseline) -> 100 -> (1m, cool-down) -> 0"
  lifecycle_orders_per_batch: 4
  telemetry_interval_seconds: 10
  tick_interval_millis: 100
  diagnostics_blob_size: 256
