process_names:
  - name: redpanda
    comm:
      - redpanda
  - name: apache-kafka
    comm:
      - java
    cmdline:
      - kafka\.Kafka
  - name: ckc-demo
    comm:
      - java
    cmdline:
      - avh\.ckc\.demo\.DemoApplicationKt
  - name: ckc-load-test
    comm:
      - java
    cmdline:
      - avh\.ckc\.loadtest\.LoadTestApplicationKt
  - name: redis
    comm:
      - redis-server
