thread-stats.agent.bind=0.0.0.0
thread-stats.agent.port=9404
thread-stats.agent.prometheus-path=/prometheus
thread-stats.agent.report-path=/threadstats
thread-stats.agent.interval=5s
thread-stats.agent.fallback-group=other

thread-stats.agent.rule.0.group=thread-stats-agent
thread-stats.agent.rule.0.type=regex
thread-stats.agent.rule.0.value=thread-stats-.*

thread-stats.agent.rule.1.group=jvm-system
thread-stats.agent.rule.1.type=regex
thread-stats.agent.rule.1.value=(main|Reference Handler|Finalizer|Signal Dispatcher|Common-Cleaner|Notification Thread|RMI TCP Accept-.*|SensorExpiryThread|idle-timeout-task)

thread-stats.agent.rule.2.group=kafka-request
thread-stats.agent.rule.2.type=regex
thread-stats.agent.rule.2.value=.*kafka-request-handler.*

thread-stats.agent.rule.3.group=kafka-network
thread-stats.agent.rule.3.type=regex
thread-stats.agent.rule.3.value=.*kafka-network-thread.*

thread-stats.agent.rule.4.group=kafka-acceptor
thread-stats.agent.rule.4.type=regex
thread-stats.agent.rule.4.value=.*kafka-socket-acceptor.*

thread-stats.agent.rule.5.group=kafka-raft
thread-stats.agent.rule.5.type=regex
thread-stats.agent.rule.5.value=.*raft.*

thread-stats.agent.rule.6.group=kafka-coordinator
thread-stats.agent.rule.6.type=regex
thread-stats.agent.rule.6.value=.*[Cc]oordinator.*

thread-stats.agent.rule.7.group=kafka-controller
thread-stats.agent.rule.7.type=regex
thread-stats.agent.rule.7.value=.*[Cc]ontroller.*

thread-stats.agent.rule.8.group=kafka-scheduler
thread-stats.agent.rule.8.type=regex
thread-stats.agent.rule.8.value=.*[Ss]cheduler.*

thread-stats.agent.rule.9.group=kafka-log
thread-stats.agent.rule.9.type=regex
thread-stats.agent.rule.9.value=.*[Ll]og.*

thread-stats.agent.rule.10.group=kafka-reaper
thread-stats.agent.rule.10.type=regex
thread-stats.agent.rule.10.value=.*([Rr]eaper|ThrottledChannelReaper).*

thread-stats.agent.rule.11.group=kafka-transaction
thread-stats.agent.rule.11.type=regex
thread-stats.agent.rule.11.value=.*(Txn|Transaction|transaction).*

thread-stats.agent.rule.12.group=kafka-metadata
thread-stats.agent.rule.12.type=regex
thread-stats.agent.rule.12.value=.*(metadata|snapshot|directory-assignments|alter-partition).*

thread-stats.agent.rule.13.group=kafka-lifecycle
thread-stats.agent.rule.13.type=regex
thread-stats.agent.rule.13.value=.*lifecycle.*

thread-stats.agent.rule.14.group=kafka-metrics
thread-stats.agent.rule.14.type=regex
thread-stats.agent.rule.14.value=.*metrics.*

thread-stats.agent.rule.15.group=kafka-persister
thread-stats.agent.rule.15.type=regex
thread-stats.agent.rule.15.value=.*[Pp]ersister.*

thread-stats.agent.rule.16.group=kafka-fetch
thread-stats.agent.rule.16.type=regex
thread-stats.agent.rule.16.value=.*[Ff]etch.*

thread-stats.agent.rule.17.group=jdk-http-server
thread-stats.agent.rule.17.type=exact
thread-stats.agent.rule.17.value=HTTP-Dispatcher
