thread-stats.agent.bind=0.0.0.0
thread-stats.agent.port=9404
thread-stats.agent.prometheus-path=/prometheus
thread-stats.agent.report-path=/threadstats
thread-stats.agent.interval=5s
thread-stats.agent.category-order-prefix-enabled=true
thread-stats.agent.fallback-category=other
thread-stats.agent.fallback-group=other

thread-stats.agent.category.0.name=thread-stats
thread-stats.agent.category.0.group.0.name=thread-stats-agent
thread-stats.agent.category.0.group.0.rule.0.type=regex
thread-stats.agent.category.0.group.0.rule.0.value=thread-stats-.*

thread-stats.agent.category.1.name=jvm
thread-stats.agent.category.1.group.0.name=jvm-system
thread-stats.agent.category.1.group.0.rule.0.type=regex
thread-stats.agent.category.1.group.0.rule.0.value=(main|Reference Handler|Finalizer|Signal Dispatcher|Common-Cleaner|Notification Thread|RMI TCP Accept-.*|SensorExpiryThread|idle-timeout-task)

thread-stats.agent.category.2.name=kafka
thread-stats.agent.category.2.group.0.name=kafka-request
thread-stats.agent.category.2.group.0.rule.0.type=regex
thread-stats.agent.category.2.group.0.rule.0.value=.*kafka-request-handler.*

thread-stats.agent.category.2.group.1.name=kafka-network
thread-stats.agent.category.2.group.1.rule.0.type=regex
thread-stats.agent.category.2.group.1.rule.0.value=.*kafka-network-thread.*

thread-stats.agent.category.2.group.2.name=kafka-acceptor
thread-stats.agent.category.2.group.2.rule.0.type=regex
thread-stats.agent.category.2.group.2.rule.0.value=.*kafka-socket-acceptor.*

thread-stats.agent.category.2.group.3.name=kafka-raft
thread-stats.agent.category.2.group.3.rule.0.type=regex
thread-stats.agent.category.2.group.3.rule.0.value=.*raft.*

thread-stats.agent.category.2.group.4.name=kafka-coordinator
thread-stats.agent.category.2.group.4.rule.0.type=regex
thread-stats.agent.category.2.group.4.rule.0.value=.*[Cc]oordinator.*

thread-stats.agent.category.2.group.5.name=kafka-controller
thread-stats.agent.category.2.group.5.rule.0.type=regex
thread-stats.agent.category.2.group.5.rule.0.value=.*[Cc]ontroller.*

thread-stats.agent.category.2.group.6.name=kafka-scheduler
thread-stats.agent.category.2.group.6.rule.0.type=regex
thread-stats.agent.category.2.group.6.rule.0.value=.*[Ss]cheduler.*

thread-stats.agent.category.2.group.7.name=kafka-log
thread-stats.agent.category.2.group.7.rule.0.type=regex
thread-stats.agent.category.2.group.7.rule.0.value=.*[Ll]og.*

thread-stats.agent.category.2.group.8.name=kafka-reaper
thread-stats.agent.category.2.group.8.rule.0.type=regex
thread-stats.agent.category.2.group.8.rule.0.value=.*([Rr]eaper|ThrottledChannelReaper).*

thread-stats.agent.category.2.group.9.name=kafka-transaction
thread-stats.agent.category.2.group.9.rule.0.type=regex
thread-stats.agent.category.2.group.9.rule.0.value=.*(Txn|Transaction|transaction).*

thread-stats.agent.category.2.group.10.name=kafka-metadata
thread-stats.agent.category.2.group.10.rule.0.type=regex
thread-stats.agent.category.2.group.10.rule.0.value=.*(metadata|snapshot|directory-assignments|alter-partition).*

thread-stats.agent.category.2.group.11.name=kafka-lifecycle
thread-stats.agent.category.2.group.11.rule.0.type=regex
thread-stats.agent.category.2.group.11.rule.0.value=.*lifecycle.*

thread-stats.agent.category.2.group.12.name=kafka-metrics
thread-stats.agent.category.2.group.12.rule.0.type=regex
thread-stats.agent.category.2.group.12.rule.0.value=.*metrics.*

thread-stats.agent.category.2.group.13.name=kafka-persister
thread-stats.agent.category.2.group.13.rule.0.type=regex
thread-stats.agent.category.2.group.13.rule.0.value=.*[Pp]ersister.*

thread-stats.agent.category.2.group.14.name=kafka-fetch
thread-stats.agent.category.2.group.14.rule.0.type=regex
thread-stats.agent.category.2.group.14.rule.0.value=.*[Ff]etch.*

thread-stats.agent.category.3.name=http
thread-stats.agent.category.3.group.0.name=jdk-http-server
thread-stats.agent.category.3.group.0.rule.0.type=exact
thread-stats.agent.category.3.group.0.rule.0.value=HTTP-Dispatcher
